### ISSUE TITLE
Issue with Firefox browser in displaying the countdown

### ISSUE THREAD

**Issue by hemantvikram** [clemdesign/angular-cd-timer#43]
Hi Team,

This issue can be easily reproduced in firefox browser. Just open http://angular-cd-timer.clemdesign.fr/ link in two or three tabs of firefox browser. Under **basic example**, click the **start** button visiting all tabs and stay in the last tab for a while. Note down the seconds elapsed and then switch to the first tab, you will see that even-though we have started first in first tab, it is lagging behind the last tab which was active for a while.

Thanks,
Hemant.

**Comment by clemdesign** [comment]
`angular-cd-timer` is not real time based timer, but based on tick count that depends of your environment system.

So, it's possible to have lag if JavaScript engine is busy when tick received by system.

I close this issue because the better way to manage this is to propose a PR in order to change count strategy.

**Comment by hemantvikram** [comment]
Hi @clemdesign ,
 Since the control is a timer control, it must be obeying time principle. This is what I feel. I don't know what PR is or how it can help. Just thought I should update you.
Thanks,
Hemant.
